baseURL = 'https://swift-hep.github.io'
languageCode = 'en-us'
title = 'SWIFT-HEP'

theme = "swift-hep"
relativeURLS = true

staticDir = ['static']

pygmentsCodeFences = true
pygmentsUseClasses = true

[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"

[markup.goldmark.renderer]
unsafe = true

[params]
description = "SoftWare and InFrastruture Technology for High Energy Physics"
github_org = "https://github.com/swift-hep"

sectionPagesMenu = "main"
[menu]
  [[menu.main]]
     identifier = "workpackages"
     title = "Work Packages"
     url = "/workpackages/"
     weight = 150
 [[menu.main]]
     identifier = "overview"
     title = "Overview"
     url = "/overview/"
     weight = 100
 [[menu.main]]
     identifier = "organisation"
     title = "Organisation"
     url = "/organisation/"
     weight = 200
 [[menu.main]]
     identifier = "meetings"
     title = "Meetings"
     url = "https://indico.cern.ch/category/11790/"
     weight = 220
 [[menu.main]]
     identifier = "jobs"
     title = "Jobs"
     url = "/jobs/"
     weight = 230
 [[menu.main]]
     identifier = "links"
     title = "Links"
     url = "/links/"
     weight = 240

